config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
  length: {minimum:3, maximum:15}, uniqueness: { case_sensitive: false }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.all
  end

  def show 
    @messages = Message.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private 

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new 
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in!"
      redirect_to root_path
    else
      flash.now[:danger] = "There was something wrong with your login credentials"
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out."
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:warning] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 align="center">
  <div class="chatroom-icon"></div>
  Say something!
</h4>
<div class="row">
    <div class="col-10">
      <div class="card chatbox">
        <div class="card-body" id="messages">
          <div class="ui small feed" id="message-container">
            <%= render @messages%>
          </div>
        </div>
        <div class="chatbox-divider"></div>
         <%= form_for(@message, html: {role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="card-body input-field">
            <div class="input-group mb-3">
              <%= f.text_field :body, placeholder: "Enter a message...", class: "form-control" %>
              <div class="input-group-append">
                <%= f.button '<div class=""></div>'.html_safe, class: "btn btn-outline-secondary btn-icon" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-2">
      <div class="card chatbox">
        <div class="card-body">
          <div class="users-menu">
            <span class="dropdown-item-text">Online Users</span>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
    <%= message_content %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item chatroom-tab">
        <%= link_to "Chatroom", root_path, class: "nav-link" %>
      </li>
      <div class="divider"></div>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages <span class="sr-only">(current)</span></a>
      </li>
      <div class="divider"></div>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="divider left-divider"></div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Log in", login_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      </ul>
      <div class="divider right-divider"></div>
      <% if !logged_in? %>
        <%= link_to "Log in", login_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMeApp</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>:
      <%= message.body %>
    </div>
  </div>
</div>